package com.proeza.conad.entity;
// Generated Apr 11, 2020, 7:13:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * UnidadFuncional generated by hbm2java
 */
@Entity
@Table(name = "cad_unidad_funcional")
public class UnidadFuncional implements java.io.Serializable {
	private static final long	serialVersionUID	= 1L;

	public static final String	UF_DEPTO			= "UFDPTO";
	public static final String	UF_COCHE			= "UFCOCH";

	private Long				id;
	private String				codigo;
	private Double				incidencia;
	private Boolean				habilitado;
	private Consorcio			consorcio;
	private TipoUnidadFuncional	tipoUnidadFuncional;
	private Propietario			propietario;
	private Inquilino			inquilino;

	public UnidadFuncional () {
	}

	public UnidadFuncional (Consorcio consorcio, TipoUnidadFuncional tipoUnidadFuncional, String codigo) {
		this.consorcio = consorcio;
		this.tipoUnidadFuncional = tipoUnidadFuncional;
		this.codigo = codigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId () {
		return this.id;
	}

	public void setId (Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_consorcio", nullable = false)
	public Consorcio getConsorcio () {
		return this.consorcio;
	}

	public void setConsorcio (Consorcio consorcio) {
		this.consorcio = consorcio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_tipo", nullable = false)
	public TipoUnidadFuncional getTipoUnidadFuncional () {
		return this.tipoUnidadFuncional;
	}

	public void setTipoUnidadFuncional (TipoUnidadFuncional tipoUnidadFuncional) {
		this.tipoUnidadFuncional = tipoUnidadFuncional;
	}

	@Column(name = "codigo", nullable = false, length = 20)
	public String getCodigo () {
		return this.codigo;
	}

	public void setCodigo (String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "incidencia", nullable = false)
	public Double getIncidencia () {
		return this.incidencia;
	}

	public void setIncidencia (Double incidencia) {
		this.incidencia = incidencia;
	}

	@Column(name = "habilitado", nullable = false)
	public Boolean isHabilitado () {
		return this.habilitado;
	}

	public void setHabilitado (Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinTable(name = "cad_uf_propietario",
	joinColumns = {@JoinColumn(name = "fk_uf")},
	inverseJoinColumns = {@JoinColumn(name = "fk_propietario")})
	public Propietario getPropietario () {
		return this.propietario;
	}

	public void setPropietario (Propietario propietario) {
		this.propietario = propietario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinTable(name = "cad_uf_inquilino",
	joinColumns = {@JoinColumn(name = "fk_uf")},
	inverseJoinColumns = {@JoinColumn(name = "fk_inquilino")})
	public Inquilino getInquilino () {
		return this.inquilino;
	}

	public void setInquilino (Inquilino inquilino) {
		this.inquilino = inquilino;
	}
}
