package com.proeza.core.entity;
// Generated Apr 11, 2020, 7:13:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "cmn_direccion")
public class Direccion implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private Long				id;
	private String				calle;
	private Integer				numero;
	private String				localidad;
	private String				partido;
	private String				provincia;
	private String				codigoPostal;
	private Integer				piso;
	private String				departamento;
	private String				descripcion;

	public Direccion () {
	}

	public Direccion (String calle, String localidad, String partido, String provincia, String codigoPostal) {
		this.calle = calle;
		this.localidad = localidad;
		this.partido = partido;
		this.provincia = provincia;
		this.codigoPostal = codigoPostal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId () {
		return this.id;
	}

	public void setId (Long id) {
		this.id = id;
	}

	@Column(name = "calle", nullable = false, length = 100)
	public String getCalle () {
		return this.calle;
	}

	public void setCalle (String calle) {
		this.calle = calle;
	}

	@Column(name = "numero")
	public Integer getNumero () {
		return this.numero;
	}

	public void setNumero (Integer numero) {
		this.numero = numero;
	}

	@Column(name = "localidad", nullable = false, length = 100)
	public String getLocalidad () {
		return this.localidad;
	}

	public void setLocalidad (String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "partido", nullable = false, length = 100)
	public String getPartido () {
		return this.partido;
	}

	public void setPartido (String partido) {
		this.partido = partido;
	}

	@Column(name = "provincia", nullable = false, length = 100)
	public String getProvincia () {
		return this.provincia;
	}

	public void setProvincia (String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "codigo_postal", nullable = false, length = 10)
	public String getCodigoPostal () {
		return this.codigoPostal;
	}

	public void setCodigoPostal (String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "piso")
	public Integer getPiso () {
		return this.piso;
	}

	public void setPiso (Integer piso) {
		this.piso = piso;
	}

	@Column(name = "departamento", length = 5)
	public String getDepartamento () {
		return this.departamento;
	}

	public void setDepartamento (String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "descripcion", length = 1000)
	public String getDescripcion () {
		return this.descripcion;
	}

	public void setDescripcion (String descripcion) {
		this.descripcion = descripcion;
	}
}