package com.proeza.core.entity;
// Generated Apr 11, 2020, 7:13:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import static javax.persistence.GenerationType.*;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "cmn_documento", uniqueConstraints = @UniqueConstraint(columnNames = {"codigo", "fk_tipo"}))
public class Documento implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private long				id;
	private String				codigo;
	private TipoDocumento		tipoDocumento;

	public Documento () {
	}

	public Documento (long id, TipoDocumento tipoDocumento, String codigo) {
		this.id = id;
		this.tipoDocumento = tipoDocumento;
		this.codigo = codigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId () {
		return this.id;
	}

	public void setId (long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_tipo", nullable = false)
	public TipoDocumento getTipoDocumento () {
		return this.tipoDocumento;
	}

	public void setTipoDocumento (TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "codigo", nullable = false, length = 20)
	public String getCodigo () {
		return this.codigo;
	}

	public void setCodigo (String codigo) {
		this.codigo = codigo;
	}
}
