package com.proeza.core.entity;
// Generated Apr 11, 2020, 7:13:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "cmn_persona")
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class Persona implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private Long				id;
	private String				nombre;
	private String				apellido;
	private Direccion			direccion;
	private String				email;
	private String				sexo;
	private Boolean				habilitado;
	private DocumentoIdentidad			documento;
	private Telefono			telefono;
	private Foto				foto;

	public Persona () {
	}

	public Persona (String nombre, String apellido, String sexo, Boolean habilitado) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.sexo = sexo;
		this.habilitado = habilitado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId () {
		return this.id;
	}

	public void setId (Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_direccion")
	public Direccion getDireccion () {
		return this.direccion;
	}

	public void setDireccion (Direccion direccion) {
		this.direccion = direccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_documento")
	public DocumentoIdentidad getDocumento () {
		return this.documento;
	}

	public void setDocumento (DocumentoIdentidad documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_foto")
	public Foto getFoto () {
		return this.foto;
	}

	public void setFoto (Foto foto) {
		this.foto = foto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_telefono")
	public Telefono getTelefono () {
		return this.telefono;
	}

	public void setTelefono (Telefono telefono) {
		this.telefono = telefono;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre () {
		return this.nombre;
	}

	public void setNombre (String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 50)
	public String getApellido () {
		return this.apellido;
	}

	public void setApellido (String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public String getSexo () {
		return this.sexo;
	}

	public void setSexo (String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "email", length = 200)
	public String getEmail () {
		return this.email;
	}

	public void setEmail (String email) {
		this.email = email;
	}

	@Column(name = "habilitado", nullable = false, columnDefinition = "BIT")
	public Boolean isHabilitado () {
		return this.habilitado;
	}

	public void setHabilitado (Boolean habilitado) {
		this.habilitado = habilitado;
	}
}
