package com.proeza.core.entity;
// Generated Apr 11, 2020, 7:13:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "cmn_telefono")
public class Telefono implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private Long				id;
	private String				prefInternacional;
	private String				prefArea;
	private String				numero;
	private TelefonoTipo		tipoTelefono;

	public Telefono () {
	}

	public Telefono (TelefonoTipo tipoTelefono, String prefInternacional, String prefArea, String numero) {
		this.tipoTelefono = tipoTelefono;
		this.prefInternacional = prefInternacional;
		this.prefArea = prefArea;
		this.numero = numero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId () {
		return this.id;
	}

	public void setId (Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_tipo", nullable = false)
	public TelefonoTipo getTipoTelefono () {
		return this.tipoTelefono;
	}

	public void setTipoTelefono (TelefonoTipo tipoTelefono) {
		this.tipoTelefono = tipoTelefono;
	}

	@Column(name = "pref_internacional", nullable = false, length = 3)
	public String getPrefInternacional () {
		return this.prefInternacional;
	}

	public void setPrefInternacional (String prefInternacional) {
		this.prefInternacional = prefInternacional;
	}

	@Column(name = "pref_area", nullable = false, length = 3)
	public String getPrefArea () {
		return this.prefArea;
	}

	public void setPrefArea (String prefArea) {
		this.prefArea = prefArea;
	}

	@Column(name = "numero", nullable = false, length = 10)
	public String getNumero () {
		return this.numero;
	}

	public void setNumero (String numero) {
		this.numero = numero;
	}

}
