package com.proeza.core.entity;
// Generated Apr 11, 2020, 7:13:39 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import static javax.persistence.GenerationType.*;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "cmn_documento_tipo", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class TipoDocumento implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private Long				id;
	private String				codigo;
	private String				nombre;
	private String				descripcion;
	private Set<DocumentoIdentidad>		documentos			= new HashSet<DocumentoIdentidad>(0);

	public TipoDocumento () {
	}

	public TipoDocumento (String codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public TipoDocumento (String codigo, String nombre, String descripcion, Set<DocumentoIdentidad> documentos) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.documentos = documentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId () {
		return this.id;
	}

	public void setId (Long id) {
		this.id = id;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo () {
		return this.codigo;
	}

	public void setCodigo (String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre () {
		return this.nombre;
	}

	public void setNombre (String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion () {
		return this.descripcion;
	}

	public void setDescripcion (String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<DocumentoIdentidad> getDocumentos () {
		return this.documentos;
	}

	public void setDocumentos (Set<DocumentoIdentidad> documentos) {
		this.documentos = documentos;
	}

}
